export const ProgramData = [
  {
    id: 1,
    image: "/avatar.jpg",
    title: "University of Lagos",
    subtitle: "Bachelor of Science (BSc) in Computer Science",
    status: "ongoing",
    bgcolor: "orange2",
    color: "orange1",
    padding: "py-0.5 px-2 rounded-xl",
  },
  {
    id: 2,
    image: "/avatar.jpg",
    title: "University of Abuja",
    subtitle: "Bachelor of Science (BSc) in Computer Science",
    status: "Completed",
    bgcolor: "green2",
    color: "green1",
    padding: "py-0.5 px-2 rounded-xl",
  },
  {
    id: 3,
    image: "/avatar.jpg",
    title: "University of Lagos",
    subtitle: "Bachelor of Science (BSc) in Computer Science",
    status: "Suspended",
    bgcolor: "green2",
    color: "green1",
    padding: "py-0.5 px-2 rounded-xl",
  },
];

export const CoursesData = [
  {
    id: 1,
    image: "/avatar.jpg",
    title: "CIPD",
    subtitle: "C++ For Dummies",
    status: "Continue",
    bgcolor: "bg-blue-700",
    color: "text-white",
    padding: "py-4 px-6 rounded-sm",
    percentage: 80,
  },
  {
    id: 2,
    image: "/avatar.jpg",
    title: "Yorkshire",
    subtitle: "Python for Data Analysis",
    status: "Continue",
    bgcolor: "bg-blue-700",
    color: "text-white",
    padding: "py-4 px-6 rounded-sm",
    percentage: 92,
  },
  {
    id: 3,
    image: "/avatar.jpg",
    title: "Google",
    subtitle: "UX Fundamentals",
    status: "Completed",
    bgcolor: "green2",
    color: "green1",
    percentage: 100,
    padding: "py-0.5 px-2 rounded-xl",
  },
];
