export const ProgramData = [
  {
    id: 1,
    image: "/bgavatar.jpg",
    title: "Anambra State University",
    subtitle: "Bachelor of Science (BSc) in Computer Science",
    status: "ongoing",
    bgcolor: "orange2",
    color: "orange1",
    padding: "py-0.5 px-2 rounded-xl",
  },
  {
    id: 2,
    image: "/bgavatar.jpg",
    title: "Abia State University",
    subtitle: "Bachelor of Science (BSc) in Human Anatomy",
    status: "Completed",
    bgcolor: "green2",
    color: "green1",
    padding: "py-0.5 px-2 rounded-xl",
  },
  {
    id: 3,
    image: "/bgavatar.jpg",
    title: "University of Lagos",
    subtitle: "Bachelor of Science (BSc) in English",
    status: "Suspended",
    bgcolor: "green2",
    color: "green1",
    padding: "py-0.5 px-2 rounded-xl",
  },
];

export const CoursesData = [
  {
    id: 1,
    name: "course",
    image: "/bgavatar.jpg",
    title: "TS-JS",
    subtitle: "Javascript made easy",
    status: "Continue",
    bgcolor: "bg-blue-700",
    color: "text-white",
    padding: "py-4 px-6 rounded-sm",
    percentage: 80,
    button: "w-full text-center",
  },
  {
    id: 2,
    name: "course",
    image: "/bgavatar.jpg",
    title: "ICT",
    subtitle: "Best Machine learning",
    status: "Continue",
    bgcolor: "bg-blue-700",
    color: "text-white",
    padding: "py-4 px-6 rounded-sm",
    percentage: 92,
    button: "w-full text-center",
  },
  {
    id: 3,
    name: "course",
    image: "/bgavatar.jpg",
    title: "Remote",
    subtitle: "Best Practices",
    status: "Completed",
    bgcolor: "green2",
    color: "green1",
    percentage: 100,
    padding: "py-0.5 px-2 rounded-xl",
  },
];
